--------------------------------------------------------------------------------
-- |
-- Module      :  Graphics.Rendering.OpenGL.GLU.Constants
-- Copyright   :  (c) Sven Panne 2002
-- License     :  BSD-style (see the file libraries/OpenGL/LICENSE)
-- 
-- Maintainer  :  sven_panne@yahoo.com
-- Stability   :  experimental
-- Portability :  portable
--
-- This purely internal module defines all numeric GLU constants, which are
-- automatically generated by ConvertEnumSpec from enumglu.spec.
--
--------------------------------------------------------------------------------

module Graphics.Rendering.OpenGL.GLU.Constants where

import Graphics.Rendering.OpenGL.GL.BasicTypes ( GLenum )

#define HOPENGL_IMPORT_ErrorCode
#define HOPENGL_IMPORT_marshalErrorCode

#define HOPENGL_IMPORT_NurbsError
#define HOPENGL_IMPORT_marshalNurbsError

#define HOPENGL_IMPORT_TessError
#define HOPENGL_IMPORT_marshalTessError

#define HOPENGL_IMPORT_QuadricDrawStyle
#define HOPENGL_IMPORT_marshalQuadricDrawStyle

#define HOPENGL_IMPORT_QuadricCallback
#define HOPENGL_IMPORT_marshalQuadricCallback

#define HOPENGL_IMPORT_QuadricNormal
#define HOPENGL_IMPORT_marshalQuadricNormal

#define HOPENGL_IMPORT_QuadricOrientation
#define HOPENGL_IMPORT_marshalQuadricOrientation

#define HOPENGL_IMPORT_TessCallback
#define HOPENGL_IMPORT_marshalTessCallback

#define HOPENGL_IMPORT_TessProperty
#define HOPENGL_IMPORT_marshalTessProperty

#define HOPENGL_IMPORT_TessWinding
#define HOPENGL_IMPORT_marshalTessWinding

#define HOPENGL_IMPORT_StringName
#define HOPENGL_IMPORT_marshalStringName

#include "Constants.incl"
