--------------------------------------------------------------------------------
-- |
-- Module      :  Graphics.Rendering.OpenGL.GL.Constants
-- Copyright   :  (c) Sven Panne 2003
-- License     :  BSD-style (see the file libraries/OpenGL/LICENSE)
-- 
-- Maintainer  :  sven_panne@yahoo.com
-- Stability   :  experimental
-- Portability :  portable
--
-- This purely internal module defines all numeric GL constants.
-- Automatically generated by ConvertEnumSpec from enumgl.spec.
--
--------------------------------------------------------------------------------

module Graphics.Rendering.OpenGL.GL.Constants where

import Graphics.Rendering.OpenGL.GL.BasicTypes ( GLenum, GLbitfield )

#include "Constants.incl"
