# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.1 2003/01/24 18:54:37 panne Exp $

TOP = ../..
include $(TOP)/mk/boilerplate.mk

H_FILES = $(wildcard *.h)

includedir = $(libdir)/include
INSTALL_INCLUDES = $(H_FILES)

include $(TOP)/mk/target.mk
