# -----------------------------------------------------------------------------
# $Id: Makefile,v 1.4 2002/05/31 12:28:19 panne Exp $

TOP = ../../..
include $(TOP)/mk/boilerplate.mk

# -----------------------------------------------------------------------------

HC           = $(GHC_INPLACE)
MKDEPENDHS   = $(GHC_INPLACE)
HS_PROG      = ConvertSpec
CLEAN_FILES += Main.hi

# -----------------------------------------------------------------------------

include $(TOP)/mk/target.mk
